module.exports = {
  Docs: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the current docs folder
    },
    {
      type: 'link',
      href: '/About',
      label: 'About Us',   
    },    
    {
      type: 'link',
      label: 'You Tube',
      href: 'https://www.youtube.com/@Code-Mastermind-HQ',
    },
    {
      type: 'link',
      label: 'Chat with us on Discord',
      href: 'https://discord.com/invite/BFkPKMsfuZ',
    },
  ],
};